-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2016-11-22 14:55:16 EST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

--CREATE DATABASE e-ticket;

CREATE TABLE Addresse
  (
    NoCivique  INTEGER NOT NULL ,
    Rue        VARCHAR2 (256) NOT NULL ,
    CodePostal VARCHAR2 (6) NOT NULL ,
    Ville      VARCHAR2 (20) NOT NULL ,
    Province   VARCHAR2 (40) NOT NULL ,
    NoAddresse INTEGER NOT NULL
  ) ;
ALTER TABLE Addresse ADD CONSTRAINT Locations_PK PRIMARY KEY ( NoAddresse ) ;


CREATE TABLE Categorie
  ( Nom VARCHAR2 (50) NOT NULL , Parent VARCHAR2 (50)
  ) ;
ALTER TABLE Categorie ADD CONSTRAINT Categorie_PK PRIMARY KEY ( Nom ) ;


CREATE TABLE Client
  (
    NomUtilisateur VARCHAR2 (20) NOT NULL ,
    MotDePasse     VARCHAR2 (20) ,
    Nom            VARCHAR2 (20) ,
    Prenom         VARCHAR2 (20) ,
    NoClient       INTEGER NOT NULL ,
    NoAddresse     INTEGER ,
    Code           INTEGER
  ) ;
ALTER TABLE Client ADD CONSTRAINT Clients_PK PRIMARY KEY ( NoClient ) ;


CREATE TABLE Coupon
  (
    Rabais     NUMBER (3,2) NOT NULL ,
    Code       INTEGER NOT NULL ,
    Expiration DATE ,
    Nom        VARCHAR2 (10)
  ) ;
ALTER TABLE Coupon ADD CONSTRAINT Coupon_PK PRIMARY KEY ( Code ) ;


CREATE TABLE Emplacement
  (
    NoEmplacement INTEGER NOT NULL ,
    Nom           VARCHAR2 (50) ,
    SiteWeb       VARCHAR2 (256) ,
    Capacite      INTEGER ,
    Courriel      VARCHAR2 (256) ,
    NoAddresse    INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX Emplacement__IDX ON Emplacement
  (
    NoAddresse ASC
  )
  ;
ALTER TABLE Emplacement ADD CONSTRAINT Emplacement_PK PRIMARY KEY ( NoEmplacement ) ;


CREATE TABLE Evenement
  (
    NoEvenement INTEGER NOT NULL ,
    Titre       VARCHAR2 (50) NOT NULL ,
    Description VARCHAR2 (512) ,
    SiteWeb     VARCHAR2 (256) ,
    Duree INTERVAL DAY (9) TO SECOND (0) NOT NULL ,
    ImageAffiche BLOB ,
    Nom VARCHAR2 (50)
  ) ;
CREATE UNIQUE INDEX Evenement__IDX ON Evenement
  (
    Nom ASC
  )
  ;
ALTER TABLE Evenement ADD CONSTRAINT Evenement_PK PRIMARY KEY ( NoEvenement ) ;


CREATE TABLE Occurence
  (
    NoOccurence INTEGER NOT NULL ,
    DateEtHeure DATE ,
    Prix        NUMBER (10,2) ,
    NoEvenement INTEGER
  ) ;
ALTER TABLE Occurence ADD CONSTRAINT Occurence_PK PRIMARY KEY ( NoOccurence ) ;


CREATE TABLE Transaction
  (
    NoTransaction INTEGER NOT NULL ,
    Statut        VARCHAR2 (9) DEFAULT 'en attente' NOT NULL ,
    Coût          NUMBER NOT NULL ,
    "Date"        DATE NOT NULL ,
    ModePaiement  VARCHAR2 (8 CHAR) NOT NULL ,
    MontantPayé   NUMBER NOT NULL ,
    Billets       INTEGER NOT NULL ,
    NoClient      INTEGER ,
    NoOccurence   INTEGER
  ) ;
ALTER TABLE Transaction ADD CHECK ( Statut       IN ('annulée', 'approuvée', 'en attente', 'payée')) ;
ALTER TABLE Transaction ADD CHECK ( ModePaiement IN ('comptant', 'crédit', 'débit')) ;
ALTER TABLE Transaction ADD CONSTRAINT Transaction_PK PRIMARY KEY ( NoTransaction ) ;


ALTER TABLE Client ADD CONSTRAINT ClientAddresse FOREIGN KEY ( NoAddresse ) REFERENCES Addresse ( NoAddresse ) ;

ALTER TABLE Transaction ADD CONSTRAINT ClientTransactions FOREIGN KEY ( NoClient ) REFERENCES Client ( NoClient ) ;

ALTER TABLE Client ADD CONSTRAINT CouponTransaction FOREIGN KEY ( Code ) REFERENCES Coupon ( Code ) ;

ALTER TABLE Emplacement ADD CONSTRAINT EmplacementAddresse FOREIGN KEY ( NoAddresse ) REFERENCES Addresse ( NoAddresse ) ;

ALTER TABLE Occurence ADD CONSTRAINT EvenementOccurence FOREIGN KEY ( NoEvenement ) REFERENCES Evenement ( NoEvenement ) ON
DELETE CASCADE ;

ALTER TABLE Transaction ADD CONSTRAINT OccurenceTransactions FOREIGN KEY ( NoOccurence ) REFERENCES Occurence ( NoOccurence ) ;

ALTER TABLE Categorie ADD CONSTRAINT "Sous-categorie" FOREIGN KEY ( Parent ) REFERENCES Categorie ( Nom ) ;

ALTER TABLE Evenement ADD CONSTRAINT ÉvènementCatégorie FOREIGN KEY ( Nom ) REFERENCES Categorie ( Nom ) ;

CREATE OR REPLACE TRIGGER FKNTO_Client BEFORE
  UPDATE OF NoAddresse ON Client FOR EACH ROW BEGIN IF :old.NoAddresse IS NOT NULL THEN raise_application_error(-20225,'Non Transferable FK constraint ClientAddresse on table Client is violated');
END IF;
END;
/

CREATE OR REPLACE TRIGGER FKNTO_Transaction BEFORE
  UPDATE OF NoClient,
    NoOccurence ON Transaction FOR EACH ROW BEGIN IF :old.NoClient IS NOT NULL THEN raise_application_error(-20225,'Non Transferable FK constraint ClientTransactions on table Transaction is violated');
END IF;
IF :old.NoOccurence IS NOT NULL THEN
  raise_application_error(-20225,'Non Transferable FK constraint OccurenceTransactions on table Transaction is violated');
END IF;
END;
/


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             2
-- ALTER TABLE                             18
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           2
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
